export const cars = [
    {
        id:"1",
        percentRecommends:"64",
        pictureCard:"../images/BMW_X1.png",
        year:"2023",
        brand:"BMW X1",
        make:"BMW",
        model:"X1",
        fuelType:"Petrol",
        mileage:"16-20",
        transmission:"Automatic",
        bodyType:"SUV",
        miles:"132",
        price:"32",
        cost:"38,600"
    },
    {
        id:"2",
        percentRecommends:"94",
        pictureCard:"../images/Lamborghini_Urus.png",
        year:"2023",
        brand:"Lamborghini Urus",
        make:"Lamborghini",
        model:"Urus",
        fuelType:"Petrol",
        mileage:"16-20",
        transmission:"Automatic",
        bodyType:"SUV",
        miles:"232",
        price:"42",
        cost:"235,000"
    },
    {
        id:"3",
        percentRecommends:"89",
        pictureCard:"../images/Volvo_XC_90.png",
        year:"2023",
        brand:"Volvo XC90",
        make:"Volvo",
        model:"XC90",
        fuelType:"Petrol",
        mileage:"16-20",
        transmission:"Automatic",
        bodyType:"SUV",
        miles:"532",
        price:"55",
    },
    {
        id:"4",
        percentRecommends:"56",
        pictureCard:"../images/Jeep_Rubicon.png",
        year:"2023",
        brand:"Jeep Rubicon",
        make:"Jeep",
        model:"Rubicon",
        fuelType:"Petrol",
        mileage:"16-20",
        transmission:"Automatic",
        bodyType:"SUV",
        miles:"350",
        price:"29",
        cost:"60,000"
    },
    {
        id:"5",
        percentRecommends:"69",
        pictureCard:"../images/Mercedes-Benz_AMG_G_63.png",
        year:"2023",
        brand:"Mercedes-Benz AMG G 63",
        make:"Mercedes-Benz",
        model:"AMG G 63",
        fuelType:"Petrol",
        mileage:"16-20",
        transmission:"Automatic",
        bodyType:"SUV",
        miles:"769",
        price:"26",
        cost:"186,100"
    },
    {
        id:"6",
        percentRecommends:"75",
        pictureCard:"../images/Porsche_911_GT3_RS.png",
        year:"2023",
        brand:"Porsche 911 GT3 RS",
        make:"Porsche",
        model:"911 GT3 RS",
        fuelType:"Petrol",
        mileage:"16-20",
        transmission:"Automatic",
        bodyType:"SPORTS CAR",
        miles:"852",
        price:"15",
        cost:"224,495"
    },
    {
        id:"7",
        percentRecommends:"56",
        pictureCard:"../images/BMW_M5.png",
        year:"2023",
        brand:"BMW X5",
        make:"BMW",
        model:"X5",
        fuelType:"Petrol",
        mileage:"16-20",
        transmission:"Automatic",
        bodyType:"SEDAN",
        miles:"950",
        price:"35",
        cost:"123,275"
    },
    {
        id:"8",
        percentRecommends:"69",
        pictureCard:"../images/Lamborghini_Aventador.png",
        year:"2023",
        brand:"Lamborghini Aventador",
        make:"Lamborghini",
        model:"Aventador",
        fuelType:"Petrol",
        mileage:"16-20",
        transmission:"Automatic",
        bodyType:"SPORTS CAR",
        miles:"740",
        price:"12",
        cost:"507,353"
    },
    {
        id:"9",
        percentRecommends:"75",
        pictureCard:"../images/Mercedes-Benz_AMG_GT.png",
        year:"2023",
        brand:"Mercedes-Benz AMG GT",
        make:"Mercedes-Benz",
        model:"AMG GT",
        fuelType:"Petrol",
        mileage:"16-20",
        transmission:"Automatic",
        bodyType:"SPORTS CAR",
        miles:"732",
        price:"10",
        cost:"138,600"
    },
]